// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadIQ.Api.Data;

#nullable disable

namespace RoadIQ.Api.Migrations
{
    [DbContext(typeof(RoadIqDbContext))]
    partial class RoadIqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RoadIQ.Api.Models.RoadSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("LatEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("LatStart")
                        .HasColumnType("REAL");

                    b.Property<double>("LonEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("LonStart")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RoadSegments");
                });

            modelBuilder.Entity("RoadIQ.Api.Models.RoadWearSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoadSegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WearIndex")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RoadSegmentId");

                    b.ToTable("RoadWearSnapshots");
                });

            modelBuilder.Entity("RoadIQ.Api.Models.RoadWearSnapshot", b =>
                {
                    b.HasOne("RoadIQ.Api.Models.RoadSegment", "RoadSegment")
                        .WithMany("WearSnapshots")
                        .HasForeignKey("RoadSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadSegment");
                });

            modelBuilder.Entity("RoadIQ.Api.Models.RoadSegment", b =>
                {
                    b.Navigation("WearSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
